name: Publish Docker image

on: 
  push:
    branches: main

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          #repo-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: foxbandykoot/tp_ci_cd/tp_ci_cd_image
          tag_with_ref: true