name: workflow_tp

on:
  
  push: 
    branches:
      -develop
  
#   pull_request:
#     branches:
#       -main
      
#   page_build:
#   release:
#     types: # This configuration does not affect the page_build event above
#       - created

    
jobs:
  
  job2:
    name: job2
    
    runs-on: ubuntu-latest
    
    environment: staging_environment
    
    outputs:
      output1: ${{ steps.step1.outputs.test }}

    steps:
        - id: step1
#           run: echo "::set-output name=test::hello"
          run: echo "BONJOUR"

#     environment:
#       name: production_environment
#       url: https://github.com
  
#   build:
  
#     env:
#       SERVER: production
      
#     defaults:
#       run:
#         shell: bash
#         working-directory: scripts
        
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag TP_CI_CD_ISO:$(date +%s)
